<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActeursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeursRepository extends EntityRepository
{
    public function getNombreActeurs()
    {
        $query = $this->getEntityManager()->createQuery(

        // nombre de acteurs

            "SELECT COUNT(a) FROM TroiswaBackBundle:Acteurs a"      // Acteurs est ma class Acteurs dans 'Entity/Acteurs.php'
        );

        //die(var_dump(getSingleScalarResult()));                   // idem fetchcolumn()
        return $query->getSingleScalarResult();
    }

}
