<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmsRepository extends EntityRepository  // c'est dans FilmsRepository que l'on met les requetes
{

    public function getNombreDeFilms()
    {
        $query = $this->getEntityManager()->createQuery(

            // nombre de films
            "SELECT COUNT(f) FROM TroiswaBackBundle:Films f"        // Films est ma class Films dans 'Entity/Films.php

        );

        //die(var_dump(getSingleScalarResult()));                   // idem fetchcolumn()
        return $query->getSingleScalarResult();
    }

    public function getAllFilms()
    {
        $query = $this->getEntityManager()->createQuery(
            // affiche tous les films
            "SELECT f FROM TroiswaBackBundle:Films f"
         );

        //die(var_dump($query->getResult()));                           // idem fetchall()
        return $query->getResult();                                    // idem fetchall()
    }



    public function getBestFilm()
    {
        $query = $this->getEntityManager()->createQuery(

            // meilleur film
            "SELECT f FROM TroiswaBackBundle:Films f ORDER BY f.note DESC"
        );

        //die(var_dump($query->setMaxResults(1)->getSingleResult())); Max=1 car c'est le meilleur que l'on veut seulement
        return $query->setMaxResults(1)->getSingleResult();
    }





    public function getFilmGenre($type)
    {
        $query = $this->getEntityManager()->createQuery(

            // Nombre de films par genre

            //"SELECT COUNT(f),g.type FROM TroiswaBackBundle:Films f JOIN f.genre g GROUP BY g.type"

            "SELECT COUNT(f),g.type FROM TroiswaBackBundle:Films f JOIN f.genre g WHERE g.type=:letype"
        );

        //die(var_dump($query->getResult()));                         // idem fetchall()
        //return $query->getResult();                                  // idem fetchall()

        //die(var_dump($query->setParameter("letype",$type)->getresult() ));
        return $query->setParameter("letype",$type)->getresult();
    }


    public function getLastFilms($nb)
    {
        $query = $this->getEntityManager()->createQuery(

            // Les 5 derniers films par rapport a la date
            "SELECT f FROM TroiswaBackBundle:Films f ORDER BY f.dateDeRealisation DESC"

        );
        //die(var_dump($query->setMaxResults(5)->getResult()));
        return $query->setMaxResults($nb)->getResult();
    }


    public function getHommesFemmes()
    {
        $query = $this->getEntityManager()->createQuery(
            // Le nombre Hommes et femmes
            "SELECT COUNT(a),a.sexe FROM TroiswaBackBundle:Acteurs a GROUP BY a.sexe"
        );

        //die(var_dump($query->getResult()));                           // idem fetchall()
        return $query->getResult();                                    // idem fetchall()
    }
}
