<?php

namespace Troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenresRepository extends EntityRepository
{

    public function getNombreGenres()
    {
        $query = $this->getEntityManager()->createQuery(

        // nombre de films
            "SELECT COUNT(g) FROM TroiswaBackBundle:Genres g"        // Genres est ma class Genres dans 'Entity/genres.php

        );

        //die(var_dump(getSingleScalarResult()));                   // idem fetchcolumn()
        return $query->getSingleScalarResult();
    }

}
